### ISSUE TITLE
Download failed.

### ISSUE THREAD

**Issue by Aangoan** [secuvera/SpotMyBackup#12]
Hey
Today I tried to export all my playlists when I click download it gives me an error?
It's
277 playlists
22625 tracks
Is it too much?

**Comment by Reflector92** [comment]
Hey! Also having trouble exporting my playlists, I have 165 and quite alot of tracks.
I get this error from the console:
jquery-1.11.2.min.js:4 GET https://api.spotify.com/v1/users/"username"/playlists/"random numbers"/tracks?offset=1500&limit=100 429 (Too Many Requests)

So I want to be able to slow down the requests, so Im able for it to finish fetching all the songs and all the playlist in right order.
Also had problems once I managed to get it to work with Export button, download failed.

All help would be alot apriciated as Im not good with Developer console yet!

**Comment by secuvera** [comment]
Yeah, you are on the right path. You should really be able to delay the calls to the spotify api to not run into this issue. For this we will need to inject code via the Developer console to change the behaviour of the code before you run it. Two steps ...

Copy the folllowing function into the Developer console and press Enter:
function sleep(s) {
  return new Promise(resolve => setTimeout(resolve, s * 1000));
}

Now we have a function with which we can easily delay those calls. We change the existing function by doing the same as before. Copy the following function into the Developer console and press Enter:
function loadTrackChunks(url, arr, callback) {
    $.ajax({
        url: url,
        headers: {
            'Authorization': 'Bearer ' + token
        },
        success: function (data) {
            if (!data) return;
            if ('items' in data) {
                $.each(data.items, function (index, value) {
                    if(value.track !== null){
                        arr.push({ id: value.track.id, uri: value.track.uri });    
                    }else{
                        console.log("track is null", value);
                    }                    
                });
            } else {
                arr.push({ id: data.track.id, uri: data.track.uri });
            }
            if (data.next) {
		await sleep(2);
                loadTrackChunks(data.next, arr, callback);
            } else {
                callback();
            }
        }
    });
}

Here we added "await sleep(2);" which delays the recursive call of loadTrackChunks for 2 seconds. You should now be able to run the code and see that the requests are delayed by 2 seconds each. Good luck!

**Comment by Aangoan** [comment]
I've updated the post that's what i get when i try to download the export

**Comment by Aangoan** [comment]
@secuvera how do i do that?

**Comment by Reflector92** [comment]
That happens to me too. Not able to download the Export. Same thing happens to me, the "download - Failed - Network error"

**Comment by Reflector92** [comment]
Also the first code works (step 1)
Although when pasting the second code (step 2) and press enter
I get this error in the console:
"Uncaught SyntaxError: await is only valid in async function"
Tried adding "async" before function in both codes, without luck

**Comment by Reflector92** [comment]
Edit:
Tried some Google group advice, deleted all my cache and cookies, updated Chrome. Now when reaching the green "Export" button when all the playlists are loaded. I press it and get sent to a "about:blank" tab, with no downloading option, just a white page...

**Comment by Reflector92** [comment]
Edit: Tried deleting some of the playlist. When I eventually got down to 105 playlist (from 163) it finally worked, the export button downloaded all the playlist in a .json file. I then tried to recover some of the playlists through Spotifys own "Recover Playlist" menu. I went up to 115 playlists again, and was able to make another export - json file. Although above I had problems. Some of the playlist I removed contained a large number of songs (2000+) Meaning at 115 playlist, I also reduced my total tracks from 36 000 songs to 20 000, so that has alot to say I guess.

So the problems with both it stopping on "Please wait. Loading your playlists and tracks ..."
And not beeing able to download the Export has to be connected to a too large sum of songs and/or playlists. You gotta make a workaround, or make it work for many playlists and many songs, because some users have alot.
@secuvera 

Although great work so far! This is by far the best Spotify backup service. As you can get all of them at the same time, aswell as importing them all back in. Fast and easy.

**Comment by Aangoan** [comment]
Thanks for trying everything, but I think this won't work for me unfortunately, since all my music is precious to me I can't just delete stuff :/

**Comment by Reflector92** [comment]
Exactly my thought too! So thats why he gotta make a solution for many songs and playlists too. 

2nd Edit: I see also that the playlists and songs DO NOT come in the right order they were, everything is just opposite, meaning my top playlist is at the bottom, also all songs are opposite, meaning the top song in a playlist will be at the bottom. How I fixed this was: Just import 2 times, when you import the inverted playlists, they will then be inverted again, so they come out the original order, and the songs too. Clever workaround, but this should be fixed too!

**Comment by Aangoan** [comment]
Oh wow that's even worst! @secura please fix the download limit please

**Comment by secuvera** [comment]
Fix of the last response. I didn't run the code and did not have the await precondition in mind.  You won't need the first method and only override with this function:

function loadTrackChunks(url, arr, callback) {
    $.ajax({
        url: url,
        headers: {
            'Authorization': 'Bearer ' + token
        },
        success: function (data) {
            if (!data) return;
            if ('items' in data) {
                $.each(data.items, function (index, value) {
                    if(value.track !== null){
                        arr.push({ id: value.track.id, uri: value.track.uri });    
                    }else{
                        console.log("track is null", value);
                    }                    
                });
            } else {
                arr.push({ id: data.track.id, uri: data.track.uri });
            }
            if (data.next) {
				setTimeout(function() {
					loadTrackChunks(data.next, arr, callback);
				}, 2 * 1000);
            } else {
                callback();
            }
        }
    });
}

Hit me up after you tried it.

**Comment by Reflector92** [comment]
Tested this last response code. I copied and pasted into console of Developer console (F12) in Chrome, before starting the loading of tracks/playlists (before logging into the spotify window)
Script seems to be working perfectly now, as intended, with a much more slow of the loading, so it wont crash/stop!
Good job secuvara!

**Comment by baszero** [comment]
I just tried it on http://www.spotmybackup.com/ but I still get the "Network error" in Chrome.
